// Generated by PeakRDL raw-header

package top_addrmap_pkg;

localparam longint unsigned TOP_BASE_ADDR = 64'h0;
localparam longint unsigned TOP_SIZE = 64'h4;

localparam longint unsigned TOP_CTRL_BASE_ADDR = 64'h0;


typedef enum logic [3:0] {
    NOP = 4'd0,
    ADD = 4'd1,
    SUB = 4'd2,
    MUL = 4'd3,
    DIV = 4'd4,
    SQRT = 4'd5
} opcode_e;

endpackage
