// Generated by PeakRDL raw-header

#ifndef CUSTOM_H
#define CUSTOM_H

#define CUSTOM_BASE_ADDR 0x00000000
#define CUSTOM_SIZE 0x00000008

#define CUSTOM_STATUS_BASE_ADDR(status_idx) (0x00000000 + (status_idx * 0x00000004))
#define CUSTOM_STATUS_NUM 0x00000002

#define STATE__IDLE 0
#define STATE__BUSY 1

#endif /* CUSTOM_H */
