// Generated by PeakRDL raw-header

`ifndef CUSTOM_SVH
`define CUSTOM_SVH

`define CUSTOM_BASE_ADDR 64'h0
`define CUSTOM_SIZE 64'h8

`define CUSTOM_STATUS_BASE_ADDR(status_idx) (64'h0 + (status_idx * 64'h4) )
`define CUSTOM_STATUS_NUM 64'h2

`define STATE__IDLE 0
`define STATE__BUSY 1

`endif /* CUSTOM_SVH */
