// Generated by PeakRDL raw-header

package top_addrmap_pkg;

localparam longint unsigned TOP_BASE_ADDR = 64'h0;
localparam longint unsigned TOP_SIZE = 64'h180000;

localparam longint unsigned TOP_C0_BASE_ADDR = 64'h0;
localparam longint unsigned TOP_C0_SIZE = 64'h40000;
localparam longint unsigned TOP_C0_PARAM_NUMCORES = 4;
localparam longint unsigned TOP_C0_PARAM_TCDMSIZE = 131072;
localparam bit TOP_C0_PARAM_HASFPU = 1'b1;
localparam string TOP_C0_PARAM_FLAVOR = "fast";

localparam longint unsigned TOP_C0_TCDM_BASE_ADDR = 64'h20000;
localparam longint unsigned TOP_C0_TCDM_SIZE = 64'h20000;

localparam longint unsigned TOP_C1_BASE_ADDR = 64'h100000;
localparam longint unsigned TOP_C1_SIZE = 64'h80000;
localparam longint unsigned TOP_C1_PARAM_NUMCORES = 8;
localparam longint unsigned TOP_C1_PARAM_TCDMSIZE = 262144;
localparam bit TOP_C1_PARAM_HASFPU = 1'b0;
localparam string TOP_C1_PARAM_FLAVOR = "fast";

localparam longint unsigned TOP_C1_TCDM_BASE_ADDR = 64'h140000;
localparam longint unsigned TOP_C1_TCDM_SIZE = 64'h40000;

function automatic longint unsigned TOP_C0_CTRL_BASE_ADDR(input int unsigned ctrl_idx);
    return 64'h0 + (ctrl_idx * 64'h4);
endfunction
localparam longint unsigned TOP_C0_CTRL_NUM = 64'h4;
localparam longint unsigned TOP_C0_CTRL_PARAM_RESETVALUE = 0;
function automatic longint unsigned TOP_C1_CTRL_BASE_ADDR(input int unsigned ctrl_idx);
    return 64'h100000 + (ctrl_idx * 64'h4);
endfunction
localparam longint unsigned TOP_C1_CTRL_NUM = 64'h8;
localparam longint unsigned TOP_C1_CTRL_PARAM_RESETVALUE = 0;


endpackage
