# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Run Python unit tests
        run: |
          uv run --group test pytest

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Build documentation
        run: |
          uv run --group docs sphinx-build -W -b html docs docs/_build/html

  svpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format svpkg tests/picobello.rdl -o addrmap.sv
      - name: Setup Verilator
        uses: veryl-lang/setup-verilator@v2
      - name: Lint SystemVerilog Package
        run: |
          verilator --lint-only addrmap.sv

  svh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format svh tests/picobello.rdl -o addrmap.svh
      - name: Setup Verilator
        uses: veryl-lang/setup-verilator@v2
      - name: Lint SystemVerilog Package
        run: |
          verilator --lint-only tests/svh_pkg.sv -Itests

  c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format c tests/picobello.rdl -o addrmap.h
      - name: Lint C Header
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --error-exitcode=1 addrmap.h
